---
kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: ghcr.io
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      repo: ghcr.io/tustunkok/personal-blog
      auto_tag: true
      tags: latest
      cache_from: ghcr.io/tustunkok/personal-blog:latest
      pull_image: true
    when:
      event:
        - tag
