"""add fingerprint_hash to reactions

Revision ID: 1761470ca3f2
Revises: 488f9a9bdc01
Create Date: 2026-07-04 13:50:09.741221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1761470ca3f2"
down_revision: Union[str, Sequence[str], None] = "488f9a9bdc01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reactions", sa.Column("fingerprint_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_reactions_fingerprint_hash"),
        "reactions",
        ["fingerprint_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reactions_fingerprint_hash"), table_name="reactions")
    op.drop_column("reactions", "fingerprint_hash")
    # ### end Alembic commands ###
