"""add_banned_to_fingerprints

Revision ID: 488f9a9bdc01
Revises: c688143f9e73
Create Date: 2026-07-04 13:38:21.565544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "488f9a9bdc01"
down_revision: Union[str, Sequence[str], None] = "c688143f9e73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fingerprints", sa.Column("banned", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fingerprints", "banned")
    # ### end Alembic commands ###
