"""add_lat_lon_to_visits

Revision ID: 4c8785112716
Revises: 1761470ca3f2
Create Date: 2026-07-04 14:45:55.846411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c8785112716"
down_revision: Union[str, Sequence[str], None] = "1761470ca3f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visits", sa.Column("latitude", sa.Float(), nullable=True))
    op.add_column("visits", sa.Column("longitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visits", "longitude")
    op.drop_column("visits", "latitude")
    # ### end Alembic commands ###
