"""add_fingerprint_hash_to_comments

Revision ID: c688143f9e73
Revises: 5ebb3d82c433
Create Date: 2026-07-04 13:36:48.296294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c688143f9e73"
down_revision: Union[str, Sequence[str], None] = "5ebb3d82c433"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("fingerprint_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_comments_fingerprint_hash"),
        "comments",
        ["fingerprint_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_fingerprint_hash"), table_name="comments")
    op.drop_column("comments", "fingerprint_hash")
    # ### end Alembic commands ###
